---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mattias-lernia-app
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ghcr.io/mehasdagger/lernia-app:main
    importPolicy:
      importMode: Legacy
      scheduled: true
    name: main
    referencePolicy:
      type: Source

